language: csharp

sudo: false  # use the new container-based Travis infrastructure

install:
  - mkdir ~/.config/.mono/keypairs
  - chmod 700 ~/.config/.mono/keypairs
  - chmod +x ./build.sh
  
script:
  - ./build.sh

branches:
  except:
    - gh-pages
    - release
