init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildPackage
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin\Nunit.ManualTest
    name: bin
  - path: bin\*.nupkg
    
