// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NUnit.ManualTest")]
[assembly: AssemblyProductAttribute("NUnit.ManualTest")]
[assembly: AssemblyDescriptionAttribute("NUnit.ManualTest is designed to include manual tests in the NUnit Framework infrastructure.")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
    }
}
